apiVersion: v1
kind: Pod
metadata:
  name: serverapp
spec:
  containers:
    - name: serverapp
      image: lil00/webrelease:latest
      ports:
      - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: serverappsvc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: serverapp
