apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverapp
  template:
    metadata:
      labels:
        app: serverapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: serverapp
        image: lil00/webrelease:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: serverappsvc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: serverapp
